In [8]:
import numpy as np
a = np.array([
    # 0    1      2
    [0.9, 0.05, 0.05], 
    [0.25, 0.25, 0.5]])

In [9]:
a

array([[0.9 , 0.05, 0.05],
       [0.25, 0.25, 0.5 ]])

In [10]:
a.argmax(axis=1)

array([0, 2], dtype=int64)

In [11]:
a.max(axis=1)

array([0.9, 0.5])

In [12]:
def predict_probs(images):
    return np.array([
    # 0    1      2
    [0.9, 0.05, 0.05],
    [0.25, 0.25, 0.5],
    [0.99, 0.01, 0.00]])

In [13]:
predict_probs(None)

array([[0.9 , 0.05, 0.05],
       [0.25, 0.25, 0.5 ],
       [0.99, 0.01, 0.  ]])

In [14]:
def predict(images):
    return predict_probs(images).argmax(axis=1)

In [15]:
predict(None)

array([0, 2, 0], dtype=int64)

In [16]:
metadata =[{'lat': 0, 'lon': 0, 'x': 125, 'y': 50}]

In [17]:
metadata

[{'lat': 0, 'lon': 0, 'x': 125, 'y': 50}]

In [18]:
probabilities = predict_probs(None)

In [19]:
b = probabilities.max(axis=1)

In [20]:
b

array([0.9 , 0.5 , 0.99])

In [24]:
np.where(b > 0.8)[0]

array([0, 2], dtype=int64)

In [45]:
probabilities.argmax(axis=1)

array([0, 2, 0], dtype=int64)

In [44]:
slices = 

for i in np.where(b > 0.8)[0]:
    print(i)
    slices[i]

0
2


In [47]:
# Gather an input tensor
from marsvision.pipeline import Model
from marsvision.vision import DeepMarsDataset
import torch
model = Model(r"alexnet_deepmars3-25.pt")
dataset = DeepMarsDataset(r"X:\hirise-map-proj")
dataloader = torch.utils.data.DataLoader(dataset, batch_size = 4, num_workers = 4)
input_tensor = next(iter(dataloader))["image"]

c:\users\dpale\desktop\projects\marsvision\marsvision\pipeline\Model.py:56: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(yaml_cfg)
c:\users\dpale\desktop\projects\marsvision\marsvision\vision\DeepMarsDataset.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(yaml_cfg)


In [56]:
# Returns unnormalized scores per index. 
# Return this in the predict method.
import numpy as np
from torch.nn.functional import softmax

def predict_proba(input_tensor):
    output_tensor = model.model(input_tensor)
    output_tensor = softmax(output_tensor, dim=1)
    output_numpy = np.array(output_tensor.detach().numpy())
    return output_numpy

In [61]:
# Getting label predictions from predict_proba
def predict(input_tensor):
    distribution = predict_proba(input_tensor)
distribution = predict(input_tensor)
distribution

array([0, 0, 0, 0], dtype=int64)

In [84]:
# Prototype threshold by probability.
def threshold_probability(input_tensor, threshold = 0.9):
    distribution = predict_proba(input_tensor)
    return np.where(distribution > 0.9)[0]

threshold_probability(input_tensor)

array([0, 1, 2, 3], dtype=int64)